### ISSUE TITLE
ре:мастер лендинга

### ISSUE THREAD

**Issue by dcversus** [hyperloot/hyperloot.net#11]
берем страницу about из feed и делаем ее главной
потом берем страницу token из feed и делаем ее дополнительной

новый сайт работает без vue на чистой статике и простом javascript сборка через webpack

- [x] проверить все ссылки
- [x] главная кнопка на первом слайде ведет на discord
- [x] в первом блоке, на первой строчке ТОЛЬКО лого хайперлут (убрать about)
- [x] ссылки на документы должны вести на static.hyperloot.net!

**Comment by dcversus** [comment]
http://localhost:8081/ это файл \src\about.html
http://localhost:8081/token это файл \src\token.html

соотв для стилей рядом в папке лежат about.css и token.css

**Comment by dcversus** [comment]
потом как доделаем просим дизайнера и менеджеров проверить https://github.com/hyperloot/hyperloot/issues/3

**Comment by danilstoyanov** [comment]
![default](https://user-images.githubusercontent.com/18240896/46374965-c9573900-c69a-11e8-883e-81ceaadfafb9.PNG)
Необходима картинка для фона в хорошем качестве.

**Comment by danilstoyanov** [comment]
![default](https://user-images.githubusercontent.com/18240896/46375039-fa376e00-c69a-11e8-96f5-d6f1facd9bd1.PNG)
Необходима SVG картинка вместо PNG
